### ISSUE TITLE
File

### ISSUE THREAD

**Issue by SeaUrgin** [FirephoenixX02/AnticheatManager#1]
Post a jar file please

**Comment by FirephoenixX02** [comment]
I can do that in the following days

**Comment by FirephoenixX02** [comment]
> Post a jar file please

I can do that in the following days, but dont expect any real support or how to configure it. The config should be self explanatory (you are in a luckperms group with all bypass permissions for each anticheat and the plugin basically removes the one according to which anticheat you have selected temporary for your user)
Just make sure that the anticheats are correctly registered in the config

**Comment by SeaUrgin** [comment]
Can I get the jar file now?

**Comment by FirephoenixX02** [comment]
> Can I get the jar file now?

You can find the jar under [releases](https://github.com/FirephoenixX02/AnticheatManager/releases/tag/1.0)

**Comment by SeaUrgin** [comment]
ty!

**Comment by SeaUrgin** [comment]
"org.bukkit.command.CommandException: Unhandled exception executing command 'acgui' in plugin AnticheatManager v1.0
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[server.jar:git-Spigot-21fe707-741a1bd]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[server.jar:git-Spigot-21fe707-741a1bd]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[server.jar:git-Spigot-21fe707-741a1bd]
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) ~[server.jar:git-Spigot-21fe707-741a1bd]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) ~[server.jar:git-Spigot-21fe707-741a1bd]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[server.jar:git-Spigot-21fe707-741a1bd]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[server.jar:git-Spigot-21fe707-741a1bd]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) ~[server.jar:git-Spigot-21fe707-741a1bd]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) ~[server.jar:git-Spigot-21fe707-741a1bd]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) ~[server.jar:git-Spigot-21fe707-741a1bd]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) ~[server.jar:git-Spigot-21fe707-741a1bd]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) ~[server.jar:git-Spigot-21fe707-741a1bd]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) ~[server.jar:git-Spigot-21fe707-741a1bd]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.NullPointerException: Name is null
	at java.lang.Enum.valueOf(Enum.java:291) ~[?:?]
	at org.bukkit.Material.valueOf(Material.java:1) ~[server.jar:git-Spigot-21fe707-741a1bd]
	at me.firephoenix.anticheatmanager.cmds.AnticheatManagerGUI.onCommand(AnticheatManagerGUI.java:32) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[server.jar:git-Spigot-21fe707-741a1bd]
	... 15 more
"
Can I have your discord?

**Comment by FirephoenixX02** [comment]
> Can I have your discord?

niegestorben

The error seems to be a config issue. Send me your config on dc and i will take a look.
From the error i would have guessed you didnt set a material name correctly.
